version: "2"
run:
  issues-exit-code: 1
  tests: false
linters:
  enable:
    - bodyclose
    - dupl
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - lll
    - misspell
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gocyclo
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
