# golangci-lint configuration file
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false
  skip-dirs-use-default: true

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/ihatemodels/alcatraz-live
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50

output:
  print-issued-lines: true
  print-linter-name: true
  path-prefix: ""
  sort-results: true

linters:
  enable:
    - bodyclose
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - whitespace
    - funlen
    - lll
    - dupl
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
