name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  scan-secrets:
    name: Scan for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run tests
        run: go test -v ./...

  lint:
    name: Linters
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Run Linters"
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --verbose
